HRRSystem/Models/Contact.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string consubject { get; set; }
    }
}

HRRSystem/Models/Reservation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public string name { get; set; }
        public System.DateTime check_in { get; set; }
        public System.DateTime check_out { get; set; }
        public string rooms { get; set; }
        public string nic { get; set; }
        public int adults { get; set; }

       
    }

    public enum AdultsPerRoom
    {
        One,
        Two,
        Three,
        Four
    }

    public enum SelectRooms
    {
        SingleSuite,
        SingleRoom,
        DoubleRoom
    }
}

HRRSystem/Controllers/ContactController.cs
using HRRSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HRRSystem.Controllers
{
    public class ContactController : Controller
    {
        //
        // GET: /Contact/

        public ActionResult Index()
        {

            Contact contact = new Contact();
            string userName = Request.Form["userName"];
            string userEmial = Request.Form["userEmail"];
            string userMobile = Request.Form["userMobile"];
            string userSubject = Request.Form["userSubject"];
            contact.name = userName;
            contact.email = userEmial;
            contact.mobile = userMobile;
            contact.consubject = userSubject;
            HRRSEntities hrrsEntities = new HRRSEntities();
            hrrsEntities.AddContacts(contact);


            return RedirectToAction("index", "Home");
        }


    }
}

HRRSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HRRSystem.Controllers
{

        public class HomeController : Controller
        {
            //
            // GET: /Home/

            public ActionResult Index()
            {
                return View();
            }

            public ActionResult Activities()
            {
                return View();
            }
            public ActionResult Rooms()
            {
                return View();
            }
            public ActionResult Reservation()
            {
                return View();
            }
            public ActionResult Details()
            {
                return View();
            }
            public ActionResult Contact()
            {
                return View();
            }

        }
    }

HRRSystem/Controllers/ReservationController.cs
using HRRSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HRRSystem.Controllers
{
    public class ReservationController : Controller
    {
        //
        // GET: /Reservation/

        public ActionResult Index()
        {
            Reservation res = new Reservation();
            res.name = Request.Form["userName"];
            res.nic=Request.Form["userNic"];
            res.check_in = Convert.ToDateTime("02/02/2017");
            res.check_out = Convert.ToDateTime("03/02/2017");
            res.rooms = "SingleRoom";
            res.adults = 5;

            //ViewBag.Name=Request.Form["userName"];
            //ViewBag.Nic=Request.Form["userNic"];
            HRRSEntities hrrsEntites = new HRRSEntities();
            hrrsEntites.AddReservation(res);
            //return View(ViewBag);
            return RedirectToAction("index", "Home");
        }



    }

    }

HRRSystem/Views/Home/activities.cshtml
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<title>The Paradise-Hotel Website Template | Activities :: w3layouts</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
<link href="~/Content/style.css" rel="stylesheet" type="text/css" media="all" />
<script src="js/jquery.min.js"></script>
    <link type="text/css" rel="stylesheet" href="~/Content/JFGrid.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/JFFormStyle-1.css" />
		<script type="text/javascript" src="~/Scripts/JFCore.js"></script>
    <script type="text/javascript" src="~/Scripts/JFForms.js"></script>
		<!-- Set here the key for your domain in order to hide the watermark on the web server -->
		<script type="text/javascript">
			(function() {
				JC.init({
					domainKey: ''
				});
				})();
		</script>
<!--nav-->
<script>
		$(function() {
			var pull 		= $('#pull');
				menu 		= $('nav ul');
				menuHeight	= menu.height();

			$(pull).on('click', function(e) {
				e.preventDefault();
				menu.slideToggle();
			});

			$(window).resize(function(){
        		var w = $(window).width();
        		if(w > 320 && menu.is(':hidden')) {
        			menu.removeAttr('style');
        		}
    		});
		});
</script>
</head>
<body>
<!-- start header -->
<div class="header_bg">
<div class="wrap">
	<div class="header">
		<div class="logo">
            <img src="~/Images/logo.png" alt="">
		</div>
		<div class="h_right">
			<!--start menu -->
			<ul class="menu">
                <li>@Html.ActionLink("Hotel","Index")</li> |
                <li>@Html.ActionLink("Rooms & Suites", "Rooms")</li> |
                <li>@Html.ActionLink("Reservations", "Reservation")</li> |
                <li class="active">@Html.ActionLink("Activities", "Activities")</li> |
                <li>@Html.ActionLink("Contact", "Contact")</li>
			
			</ul>
			<!-- start profile_details -->
					<form class="style-1 drp_dwn">
						<div class="row">
							<div class="grid_3 columns">
								<select class="custom-select" id="select-1">
									<option selected="selected">EN</option>
									<option>USA</option>
									<option>AUS</option>
									<option>UK</option>
									<option>IND</option>
								</select>
							</div>		
						</div>		
					</form>
		</div>
		<div class="clear"></div>
		<div class="top-nav">
		<nav class="clearfix">
				<ul>
				<li class="active"><a href="index.cshtml">hotel</a></li> 
				<li><a href="rooms.cshtml">rooms & suits</a></li> 
				<li><a href="reservation.cshtml">reservation</a></li> 
				<li><a href="activities.cshtml">activities</a></li> 
				<li><a href="contact.cshtml">contact</a></li>
				</ul>
				<a href="#" id="pull">Menu</a>
			</nav>
		</div>
	</div>
</div>
</div>
<!--start main -->
<div class="main_bg">
<div class="wrap">
	<div class="main">
<!-- start main_content -->
				<ul class="service_list">
					<li>
						<div class="ser_img">
							<a href="details.html">
                                <img src="~/Images/ser_pic1.jpg" alt="" />
								<span class="next"> </span>
							</a>
						</div>	
						<a href="details.cshtml"><h3>Awtar</h3></a>
						<p class="para">Lebanese restaurant featuring a lavish selection of arabic dishes.</p>
					</li>
					<li>
						<div class="ser_img">
							<a href="details.cshtml">
                                <img src="~/Images/ser_pic2.jpg" alt="" />
								<span class="next"> </span>
							</a>
						</div>	
						<a href="details.cshtml"><h3>Panini</h3></a>
						 <p class="para">Italian café offering a selection of coffees and home-made goodies.</p>
					</li>
					<li>
						<div class="ser_img">
							<a href="details.cshtml">
                                <img src="~/Images/ser_pic3.jpg" alt="" />
								<span class="next"> </span>
							</a>
						</div>						
						 <a href="details.cshtml"><h3>Poolside restaurant</h3></a>
						 <p class="para">Offering a relaxed al fresco dining experience all day long</p>
					</li>
					<li>
						<div class="ser_img">
							<a href="details.cshtml">
                                <img src="~/Images/ser_pic4.jpg" alt="" />
								<span class="next"> </span>
							</a>
						</div>						
						<a href="details.cshtml"><h3>Cooz</h3></a>
						 <p class="para">A stylish jazz bar serving contemporary cocktails.</p>
					</li>
					
				</ul>
				<ul class="service_list top">
					<li>
						<div class="ser_img">
							<a href="details.cshtml">
                                <img src="~/Images/ser_pic5.jpg" alt="" />
								<span class="next"> </span>
							</a>
						</div>						
						 <a href="details.cshtml"><h3>PepperCrab</h3></a>
						 <p class="para">Showcasing the best of Asian and Singaporean classics.</p>
					</li>
					<li>
						<div class="ser_img">
							<a href="details.cshtml">
                                <img src="~/Images/ser_pic6.jpg" alt="" />
								<span class="next"> </span>
							</a>
						</div>						
						 <a href="details.cshtml"><h3>Vinoteca</h3></a>
						 <p class="para">A wine bar serving a delightful collection of unique Italian wines.</p>
					</li>
					<li>
						<div class="ser_img">
							<a href="details.cshtml">
                                <img src="~/Images/ser_pic7.jpg" alt="" />
								<span class="next"> </span>
							</a>
						</div>	
						 <a href="details.cshtml"><h3>Sushi</h3></a>
						<p class="para">An intimate Japanese restaurant showcases the art of sushi making.</p>
											
					</li>
					<li>
						<div class="ser_img">
							<a href="details.cshtml">
								<img src="~/Images/ser_pic8.jpg" alt="" />
								<span class="next"> </span>
							</a>
						</div>		
						 <a href="details.cshtml"><h3>Wox</h3></a>
						 <p class="para">An authentic noodle house reminiscent of hawker stands in Southeast Asia</p>
					</li>
					
				</ul>
		<div class="clear"></div>
	<!-- end main_content -->

	</div>
</div>
</div>		
<!--start main -->
<div class="footer_bg">
<div class="wrap">
<div class="footer">
			<div class="copy">
				<p class="link"><span>© All rights reserved | Template by&nbsp;<a href="http://w3layouts.com/"> W3Layouts</a></span></p>
			</div>
			<div class="f_nav">
				<ul>
                    <li>@Html.ActionLink("Hotel", "Index")</li>
                    <li>@Html.ActionLink("Rooms & Suits", "Rooms")</li>
                    <li>@Html.ActionLink("Reservation", "Reservation")</li>
                    <li>@Html.ActionLink("Contact", "Contact")</li>
				</ul>
			</div>
			<div class="soc_icons">
				<ul>
					<li><a class="icon1" href="#"></a></li>
					<li><a class="icon2" href="#"></a></li>
					<li><a class="icon3" href="#"></a></li>
					<li><a class="icon4" href="#"></a></li>
					<li><a class="icon5" href="#"></a></li>
				
				</ul>	
			</div>
			<div class="clear"></div>
</div>
</div>
</div>		
</body>
</html>

HRRSystem/Views/Home/contact.cshtml
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<title>The Paradise-Hotel Website Template | Contact :: w3layouts</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
<link href="~/Content/style.css" rel="stylesheet" type="text/css" media="all" />
    <script src="~/Scripts/jquery.min.js"></script>
<link type="text/css" rel="stylesheet" href="~/Content/JFGrid.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/JFFormStyle-1.css" />
		<script type="text/javascript" src="~/Scripts/JFCore.js"></script>
    <script type="text/javascript" src="~/Scripts/JFForms.js"></script>
		<!-- Set here the key for your domain in order to hide the watermark on the web server -->
		<script type="text/javascript">
			(function() {
				JC.init({
					domainKey: ''
				});
				})();
		</script>
<!--nav-->
<script>
		$(function() {
			var pull 		= $('#pull');
				menu 		= $('nav ul');
				menuHeight	= menu.height();

			$(pull).on('click', function(e) {
				e.preventDefault();
				menu.slideToggle();
			});

			$(window).resize(function(){
        		var w = $(window).width();
        		if(w > 320 && menu.is(':hidden')) {
        			menu.removeAttr('style');
        		}
    		});
		});
</script>
</head>
<body>
<!-- start header -->
<div class="header_bg">
<div class="wrap">
	<div class="header">
		<div class="logo">
           <img src="~/Images/logo.png" alt="">
		</div>
		<div class="h_right">
			<!--start menu -->
			<ul class="menu">
                <li>@Html.ActionLink("Hotel", "Index")</li> |
                <li>@Html.ActionLink("Rooms & Suites", "Rooms")</li> |
                <li>@Html.ActionLink("Reservations", "Reservation")</li> |
                <li>@Html.ActionLink("Activities", "Activities")</li> |
                <li class="active">@Html.ActionLink("Contact", "Contact")</li>
				
			</ul>
			<!-- start profile_details -->
					<form class="style-1 drp_dwn">
						<div class="row">
							<div class="grid_3 columns">
								<select class="custom-select" id="select-1">
									<option selected="selected">EN</option>
									<option>USA</option>
									<option>AUS</option>
									<option>UK</option>
									<option>IND</option>
								</select>
							</div>		
						</div>		
					</form>
		</div>
		<div class="clear"></div>
		<div class="top-nav">
		<nav class="clearfix">
				<ul>
				<li class="active"><a href="index.html">hotel</a></li> 
				<li><a href="rooms.html">rooms & suits</a></li> 
				<li><a href="reservation.html">reservation</a></li> 
				<li><a href="activities.html">activities</a></li> 
				<li><a href="contact.html">contact</a></li>
				</ul>
				<a href="#" id="pull">Menu</a>
			</nav>
		</div>
	</div>
</div>
</div>
<!--start main -->
<div class="main_bg">
<div class="wrap">
	<div class="main">
		<div class="contact">				
				<div class="contact_left">
					<div class="contact_info">
			    	 	<h3>Find Us Here</h3>
			    	 		<div class="map">
					   			<iframe width="100%" height="175" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.in/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Lighthouse+Point,+FL,+United+States&amp;aq=4&amp;oq=light&amp;sll=26.275636,-80.087265&amp;sspn=0.04941,0.104628&amp;ie=UTF8&amp;hq=&amp;hnear=Lighthouse+Point,+Broward,+Florida,+United+States&amp;t=m&amp;z=14&amp;ll=26.275636,-80.087265&amp;output=embed"></iframe><br><small><a href="https://maps.google.co.in/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Lighthouse+Point,+FL,+United+States&amp;aq=4&amp;oq=light&amp;sll=26.275636,-80.087265&amp;sspn=0.04941,0.104628&amp;ie=UTF8&amp;hq=&amp;hnear=Lighthouse+Point,+Broward,+Florida,+United+States&amp;t=m&amp;z=14&amp;ll=26.275636,-80.087265" style="color: #242424;text-shadow: 0 1px 0 #ffffff;text-align: left;font-size: 0.7125em;padding: 5px;font-weight: 600;">View Larger Map</a></small>
					   		</div>
      				</div>
      			<div class="company_address">
				     	<h3>Company Information :</h3>
						<p>B-103 MM Alam Road,Lahore</p>
						<p>Pakistan</p>
				   		<p>Phone:(+92) 302 4001461</p>
				 	 	<p>Email: bitf14m014@pucit.edu.pk</p>
				   		<p>Follow on: www.facebook.com/</p>
				   </div>
				</div>				
				<div class="contact_right">
				  <div class="contact-form">
				  	<h3>Contact Us</h3>
              @using (Html.BeginForm("index", "Contact", FormMethod.Get))
              {
                  <div>
						    	<span>@Html.Label("Username")
                                @Html.TextBox("userName")
                                </span>

						    	
						    </div>
						    <div>
						    	<span>@Html.Label("Email")
                                @Html.TextBox("useremail")</span>
						    </div>
						    <div>
						     	<span>@Html.Label("Mobile")
                                @Html.TextBox("usermobile")</span>
						    </div>
						    <div>
						    	<span>@Html.Label("Subject")
                                @Html.TextArea("userSubject")</span>
						    </div>
						   <div>
						   		<span><input type="submit" value="submit us"></span>
						  </div>
              }
					    
				    </div>
  				</div>		
  				<div class="clear"></div>		
		  </div>
	</div>
</div>
</div>		
<!--start main -->
<div class="footer_bg">
<div class="wrap">
<div class="footer">
			<div class="copy">
				<p class="link"><span>© All rights reserved | Template by&nbsp;<a href="http://w3layouts.com/"> W3Layouts</a></span></p>
			</div>
			<div class="f_nav">
				<ul>
                    <li>@Html.ActionLink("Hotel", "Index")</li>
                    <li>@Html.ActionLink("Rooms & Suits", "Rooms")</li>
                    <li>@Html.ActionLink("Reservation", "Reservation")</li>
                    <li>@Html.ActionLink("Contact", "Contact")</li>
				</ul>
			</div>
			<div class="soc_icons">
				<ul>
					<li><a class="icon1" href="#"></a></li>
					<li><a class="icon2" href="#"></a></li>
					<li><a class="icon3" href="#"></a></li>
					<li><a class="icon4" href="#"></a></li>
					<li><a class="icon5" href="#"></a></li>
					
				</ul>	
			</div>
			<div class="clear"></div>
</div>
</div>
</div>		
</body>
</html>

HRRSystem/Views/Home/reservation.cshtml
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<title>The Paradise-Hotel Website Template | Reservation :: w3layouts</title>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/style.css" rel="stylesheet" type="text/css" media="all" />
<script src="~/Scripts/jquery.min.js"></script>
<!---strat-date-piker---->
    <link rel="stylesheet" href="~/Content/jquery-ui.css" />
    <script src="~/Scripts/jquery-ui.js"></script>
		  <script>
				  $(function() {
				    $( "#datepicker,#datepicker1" ).datepicker();
				  });
		  </script>
<!---/End-date-piker---->
    <link type="text/css" rel="stylesheet" href="~/Content/JFGrid.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/JFFormStyle-1.css" />
    <script type="text/javascript" src="~/Scripts/JFCore.js"></script>
    <script type="text/javascript" src="~/Scripts/JFForms.js"></script>
		<!-- Set here the key for your domain in order to hide the watermark on the web server -->
		<script type="text/javascript">
			(function() {
				JC.init({
					domainKey: ''
				});
				})();
		</script>
<!--nav-->
<script>
		$(function() {
			var pull 		= $('#pull');
				menu 		= $('nav ul');
				menuHeight	= menu.height();

			$(pull).on('click', function(e) {
				e.preventDefault();
				menu.slideToggle();
			});

			$(window).resize(function(){
        		var w = $(window).width();
        		if(w > 320 && menu.is(':hidden')) {
        			menu.removeAttr('style');
        		}
    		});
		});
</script>
</head>
<body>
<!-- start header -->
<div class="header_bg">
<div class="wrap">
	<div class="header">
		<div class="logo">
			<img src="~/Images/logo.png" alt="">
		</div>
		<div class="h_right">
			<!--start menu -->
			<ul class="menu">
                <li>@Html.ActionLink("Hotel", "Index")</li> |
                <li>@Html.ActionLink("Rooms & Suites", "Rooms")</li> |
                <li class="active">@Html.ActionLink("Reservations", "Reservation")</li> |
                <li>@Html.ActionLink("Activities", "Activities")</li> |
                <li>@Html.ActionLink("Contact", "Contact")</li>
				
			</ul>
			<!-- start profile_details -->
					<form class="style-1 drp_dwn">
						<div class="row">
							<div class="grid_3 columns">
								<select class="custom-select" id="select-1">
									<option selected="selected">EN</option>
									<option>USA</option>
									<option>AUS</option>
									<option>UK</option>
									<option>IND</option>
								</select>
							</div>		
						</div>		
					</form>
		</div>
		<div class="clear"></div>
		<div class="top-nav">
		<nav class="clearfix">
				<ul>
				<li class="active"><a href="index.html">hotel</a></li> 
				<li><a href="rooms.html">rooms & suits</a></li> 
				<li><a href="reservation.html">reservation</a></li> 
				<li><a href="activities.html">activities</a></li> 
				<li><a href="contact.html">contact</a></li>
				</ul>
				<a href="#" id="pull">Menu</a>
			</nav>
		</div>
	</div>
</div>
</div>
<!--start main -->
<div class="main_bg">
<div class="wrap">
	<div class="main">
		<div class="res_online">
			<h4>basic information</h4>
			<p class="para">Paradise Hotel has always achieved excellent international standards of quality products and services. The top hotels in Pakistan have become synonymous with a tradition of personal service, efficiency, convenience and guest satisfaction. Paradise Hotel has positioned itself as an eminently successful chain with fully owned Five Star Luxury Hotels and resorts in Pakistan. The Paradise Group is consistently focused on enhancing its brand preference by always improving the performance of the exisiting hotels’ portfolios and also successfully expanding the presence of its hotels locally, and internationally.</p>
		</div>			
			<div class="span_of_2">
				<div class="span2_of_1">
					<h4>check-in:</h4>
					<div class="book_date btm">



                        @using (Html.BeginForm("checkin", "Reservation"))
                        {
                            <div>
                                <span>
                                    <input class="date" id="datepicker1" type="text" value="DD/MM/YY" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'DD/MM/YY';}">
                            </span>

                        </div>
                            
                        }

					</div>	
					<div class="sel_room">
						<h4>number of rooms</h4>
						@Html.DropDownList("SelectRoom",
                    new SelectList(Enum.GetValues(typeof(HRRSystem.Models.SelectRooms))),
                    "Select Room",
                    new { @class = "form-control" })

					</div>	
					<div class="sel_room left">
						<h4>adults per room:</h4>
                      
						@Html.DropDownList("AdultsPerRoom",
                                               new SelectList(Enum.GetValues(typeof(HRRSystem.Models.AdultsPerRoom))),
                                               "AdultsPerRoom",
                    new { @class = "form-control" })
					</div>	
				</div>
				<div class="span2_of_1">
					<h4>check-out:</h4>
					<div class="book_date btm">

                        @using (Html.BeginForm("checkout", "Reservation"))
                        {
                            <div>
                                <span>
                                    <input class="date" id="datepicker1" type="text" value="DD/MM/YY" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'DD/MM/YY';}">
                                </span>

                            </div>

                        }
                        

					</div>	
@using (Html.BeginForm("index", "Reservation"))
{
    <div class="contact-form">
        <div>
            <span>
                @Html.Name("userName")
                @Html.Label("Name")
                @Html.TextBox("userName")
            </span>
        </div>
        <div>
            <span>
                @Html.Name("userNic")
                @Html.Label("NIC #")
                @Html.TextBox("userNic")
            </span>
        </div>
        <div>
            <input type="submit" value="book now">
        </div>
    </div>
}
    
			</div>
	</div>
</div>
</div>		
<!--start main -->
<div class="footer_bg">
<div class="wrap">
<div class="footer">
			<div class="copy">
				<p class="link"><span>© All rights reserved | Template by&nbsp;<a href="http://w3layouts.com/"> W3Layouts</a></span></p>
			</div>
			<div class="f_nav">
				<ul>
                    <li>@Html.ActionLink("Hotel", "Index")</li>
                    <li>@Html.ActionLink("Rooms & Suits", "Rooms")</li>
                    <li>@Html.ActionLink("Reservation", "Reservation")</li>
                    <li>@Html.ActionLink("Contact", "Contact")</li>
				</ul>
			</div>
			<div class="soc_icons">
				<ul>
					<li><a class="icon1" href="#"></a></li>
					<li><a class="icon2" href="#"></a></li>
					<li><a class="icon3" href="#"></a></li>
					<li><a class="icon4" href="#"></a></li>
					<li><a class="icon5" href="#"></a></li>
					
				</ul>	
			</div>
			<div class="clear"></div>
</div>
</div>
</div>		
</body>
</html>